package org.soylentred.economicworldguard;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import com.sk89q.worldguard.protection.managers.RegionManager;
import com.sk89q.worldguard.protection.managers.RemovalStrategy;
import com.sk89q.worldguard.protection.regions.ProtectedRegion;

public class commandGiveChunk implements CommandExecutor {
	public boolean debug = false;

	public commandGiveChunk(boolean debug) {
		this.debug = debug;
	}

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
		if (!(sender instanceof Player)) {
			sender.sendMessage("Command can't be used on the terminal.");
		} else {
			Player player = (Player) sender;

			if (debug) {
				Bukkit.getLogger().info("Command givechunk called by " + player.getDisplayName() + " at " + player.getLocation() + ".");
			}
			//Make sure the user is sending the chunk to a player.
			if (args.length < 1){
				Bukkit.getLogger().info("Player used the wrong syntax.");
				sender.sendMessage("Wrong syntax used. Please use /givechunk [player]");
				return true;
			}
			if(Bukkit.getPlayer(args[0]) == null){
				Bukkit.getLogger().info("Player tried to give chunk to player that doesn't exist. (" + args[0] + ")");
				sender.sendMessage("Player " + args[0] + " not found.");
				return true;
			}
				
			
			// Get player region and location
			ProtectedRegion myRegion = common.getMyRegion(player);
			int[] chunkLocation = common.getChunkLocation(player.getLocation().getBlockX(), player.getLocation().getBlockZ()); 
			if (myRegion != null){
				//Check if the chunk that is being given away is using the naming convention
				boolean usesDefaultName = common.usesNamingConvention(chunkLocation[0], chunkLocation[1], player.getName(), myRegion);
				String oldRegionName = myRegion.getId();

				//Remove region
				RegionManager regionMan = common.worldGuardInst.getRegionContainer().get(player.getWorld());
				regionMan.removeRegion(myRegion.getId(), RemovalStrategy.UNSET_PARENT_IN_CHILDREN);

				//Recreate the region in the name of the specified player
				if (usesDefaultName){
					int[] newChunkLocation = common.getChunkLocation(player.getLocation().getBlockX(), player.getLocation().getBlockZ());
					String regionName = Bukkit.getPlayer(args[0]).getName() + Integer.toString(newChunkLocation[0]) + Integer.toString(newChunkLocation[1]);
					common.createChunk(player, regionName, Bukkit.getPlayer(args[0]).getUniqueId());
				}else{
					//If the old region didn't have a name generated by economicWorldGuard then use that same ID for the new region.
					common.createChunk(player, oldRegionName, Bukkit.getPlayer(args[0]).getUniqueId());
				}
				
				player.sendMessage("Giving this chunk to " + args[0] + ".");
				if (debug) {
					Bukkit.getLogger().info("Region " + myRegion.getId() + " given to " + Bukkit.getPlayer(args[0]).toString());
				}
				return true;
			}
			
			player.sendMessage("You don't own a chunk here!");
			if (debug) {
				Bukkit.getLogger().info("No region was exchanged by givechunk command.");
			}
			return true;
		}
		return true;
	}
}