package org.soylentred.economicworldguard;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import com.sk89q.worldguard.bukkit.RegionContainer;
import com.sk89q.worldguard.bukkit.RegionQuery;
import com.sk89q.worldguard.bukkit.WorldGuardPlugin;
import com.sk89q.worldguard.protection.ApplicableRegionSet;
import com.sk89q.worldguard.protection.managers.RegionManager;
import com.sk89q.worldguard.protection.managers.RemovalStrategy;
import com.sk89q.worldguard.protection.regions.ProtectedRegion;

import net.milkbowl.vault.economy.Economy;

public class commandSellChunk implements CommandExecutor {
	public boolean debug = false;
	public WorldGuardPlugin worldGuard;
	private int sellPrice = 125;
	Economy bank;

	public commandSellChunk(boolean debug, Economy bank, int sellPrice, WorldGuardPlugin worldGuard) {
		this.debug = debug;
		this.worldGuard = worldGuard;
		this.sellPrice = sellPrice;
		this.bank = bank;
	}

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String label, String[] arg3) {
		if (!(sender instanceof Player)) {
			sender.sendMessage("Command can't be used on the terminal.");
		} else {
			Player player = (Player) sender;

			if (debug) {
				Bukkit.getLogger().info("Command SellChunk called by " + player.getDisplayName() + " at " + player.getLocation() + ".");
			}

			// Get regions at the player's location
			RegionContainer container = worldGuard.getRegionContainer();
			RegionQuery query = container.createQuery();
			ApplicableRegionSet regions = query.getApplicableRegions(player.getLocation());

			int[] chunkLocation = common.getChunkLocation(player.getLocation().getBlockX(), player.getLocation().getBlockZ());
			
			for (ProtectedRegion region : regions) {
				if (region.getId().startsWith(player.getName().toLowerCase())){
					if (region.getId().substring(player.getName().length()).equalsIgnoreCase(Integer.toString(chunkLocation[0]) + Integer.toString(chunkLocation[1]))) {
						// If the region name starts with the player's name and ends with our chunkX and chunkY then
						// assume that it was generated by economicWorldGuard and belongs to the player.
						RegionManager regionMan = container.get(player.getWorld());
						regionMan.removeRegion(region.getId(), RemovalStrategy.UNSET_PARENT_IN_CHILDREN);
						bank.depositPlayer(player, sellPrice);
						player.sendMessage("Region " + region.getId() + " sold for " + sellPrice + bank.currencyNamePlural() + ".");
						if (debug) {
							Bukkit.getLogger().info("Region " + region.getId() + " removed.");
						}
						return true;
					}
				}
			}
			player.sendMessage("You don't own a chunk here!");
			if (debug) {
				Bukkit.getLogger().info("No region was removed by sellchunk command.");
			}
			return true;
		}
		return true;
	}
}