package org.soylentred.economicworldguard;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import com.sk89q.worldedit.BlockVector;
import com.sk89q.worldguard.bukkit.RegionContainer;
import com.sk89q.worldguard.bukkit.RegionQuery;
import com.sk89q.worldguard.bukkit.WorldGuardPlugin;
import com.sk89q.worldguard.domains.DefaultDomain;
import com.sk89q.worldguard.protection.ApplicableRegionSet;
import com.sk89q.worldguard.protection.managers.RegionManager;
import com.sk89q.worldguard.protection.managers.RemovalStrategy;
import com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion;
import com.sk89q.worldguard.protection.regions.ProtectedRegion;
import com.sk89q.worldguard.protection.regions.ProtectedRegion.CircularInheritanceException;

public class commandGiveChunk implements CommandExecutor {
	public boolean debug = false;
	public WorldGuardPlugin worldGuard;

	public commandGiveChunk(boolean debug, WorldGuardPlugin worldGuard) {
		this.debug = debug;
		this.worldGuard = worldGuard;
	}

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
		if (!(sender instanceof Player)) {
			sender.sendMessage("Command can't be used on the terminal.");
		} else {
			Player player = (Player) sender;

			if (debug) {
				Bukkit.getLogger().info("Command givechunk called by " + player.getDisplayName() + " at " + player.getLocation() + ".");
			}
			//Make sure the user is sending the chunk to a player.
			if (args.length < 1){
				Bukkit.getLogger().info("Player used the wrong syntax.");
				sender.sendMessage("Wrong syntax used. Please use /givechunk [player]");
				return true;
			}
			if(Bukkit.getPlayer(args[0]) == null){
				Bukkit.getLogger().info("Player tried to give chunk to player that doesn't exist. (" + args[0] + ")");
				sender.sendMessage("Player " + args[0] + " not found.");
				return true;
			}
				
			// Get regions at the player's location
			RegionContainer container = worldGuard.getRegionContainer();
			RegionQuery query = container.createQuery();
			ApplicableRegionSet regions = query.getApplicableRegions(player.getLocation());

			int chunkX = (int) (16 * (Math.floor(Math.abs(player.getLocation().getBlockX() / 16))) / 16);
			if(player.getLocation().getBlockX() < 0){
				chunkX = chunkX * -1;
			}
			int chunkZ = (int) (16 * (Math.floor(Math.abs(player.getLocation().getBlockZ() / 16))) / 16);
			if(player.getLocation().getBlockZ() < 0){
				chunkZ = chunkZ * -1;
			}

			for (ProtectedRegion region : regions) {
				if (region.getId().startsWith(player.getName().toLowerCase())){
					if (region.getId().substring(player.getName().length()).equalsIgnoreCase(Integer.toString(chunkX) + Integer.toString(chunkZ))) {
						// If the region name starts with the player's name and ends with our chunkX and chunkY then
						// assume that it was generated by economicWorldGuard and belongs to the player.
						//Remove region
						RegionManager regionMan = container.get(player.getWorld());
						regionMan.removeRegion(region.getId(), RemovalStrategy.UNSET_PARENT_IN_CHILDREN);

						//Recreate the region in the name of the specified player
						//Collect basic info for the region
						int newChunkX = (int) (16 * (Math.floor(Math.abs(player.getLocation().getBlockX() / 16))));
						if(player.getLocation().getBlockX() < 0){
							newChunkX = (newChunkX * -1) - 15;
						}
						int newChunkZ = (int) (16 * (Math.floor(Math.abs(player.getLocation().getBlockZ() / 16))));
						if(player.getLocation().getBlockZ() < 0){
							newChunkZ = (newChunkZ * -1) - 15;
						}
						String regionName = Bukkit.getPlayer(args[0]).getName() + (newChunkX / 16) + (newChunkZ / 16);

						// Create the region
						BlockVector loc1 = new BlockVector(newChunkX, 0, newChunkZ);
						BlockVector loc2 = new BlockVector(newChunkX + 15, 256, newChunkZ + 15);
						ProtectedRegion newRegion = new ProtectedCuboidRegion(regionName, loc1, loc2);

						// Set the owner
						DefaultDomain regionOwner = new DefaultDomain();
						regionOwner.addPlayer(Bukkit.getPlayer(args[0]).getName());
						newRegion.setOwners(regionOwner);
						newRegion.setMembers(regionOwner);

						// Set the parent chunk as 'economicworldguard'
						try {
							newRegion.setParent(regionMan.getRegion("economicWorldGuard"));
						} catch (CircularInheritanceException e) {
							Bukkit.getLogger().info("Bad world.");
						}
						
						regionMan.addRegion(newRegion);
						
						player.sendMessage("Giving this chunk to " + args[0] + ".");
						if (debug) {
							Bukkit.getLogger().info("Region " + region.getId() + " given to " + Bukkit.getPlayer(args[0]).toString());
						}
						return true;
					}
				}
			}
			player.sendMessage("You don't own a chunk here!");
			if (debug) {
				Bukkit.getLogger().info("No region was exchanged by givechunk command.");
			}
			return true;
		}
		return true;
	}
}