package org.soylentred.economicworldguard;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import com.sk89q.worldguard.bukkit.RegionContainer;
import com.sk89q.worldguard.bukkit.RegionQuery;
import com.sk89q.worldguard.protection.ApplicableRegionSet;
import com.sk89q.worldguard.protection.managers.RegionManager;
import com.sk89q.worldguard.protection.regions.ProtectedRegion;
import com.sk89q.worldguard.bukkit.WorldGuardPlugin;
import com.sk89q.worldguard.domains.DefaultDomain;

public class commandShareChunk implements CommandExecutor {
	public boolean debug = false;
	public WorldGuardPlugin worldGuard;

	public commandShareChunk(boolean debug, WorldGuardPlugin worldGuard) {
		this.debug = debug;
		this.worldGuard = worldGuard;
	}

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
		if (!(sender instanceof Player)) {
			sender.sendMessage("Command can't be used on the terminal.");
		} else {
			Player player = (Player) sender;

			if (debug) {
				Bukkit.getLogger().info("Command sharechunk called by " + player.getDisplayName() + " at " + player.getLocation() + ".");
			}
			
			//Make sure the user is sharing the chunk to a player.
			if (args.length < 1){
				Bukkit.getLogger().info("Player used the wrong syntax.");
				sender.sendMessage("Wrong syntax used. Please use /sharechunk [player]");
				return true;
			}
			if(Bukkit.getPlayer(args[0]) == null){
				Bukkit.getLogger().info("Player tried to share chunk whith a player that doesn't exist. (" + args[0] + ")");
				sender.sendMessage("Player " + args[0] + " not found.");
				return true;
			}
				
			// Get regions at the player's location
			RegionContainer container = worldGuard.getRegionContainer();
			RegionQuery query = container.createQuery();
			ApplicableRegionSet regions = query.getApplicableRegions(player.getLocation());

			int chunkX = (int) (16 * (Math.floor(Math.abs(player.getLocation().getBlockX() / 16))) / 16);
			if(player.getLocation().getBlockX() < 0){
				chunkX = chunkX * -1;
			}
			int chunkZ = (int) (16 * (Math.floor(Math.abs(player.getLocation().getBlockZ() / 16))) / 16);
			if(player.getLocation().getBlockZ() < 0){
				chunkZ = chunkZ * -1;
			}

			for (ProtectedRegion region : regions) {
				if (region.getId().startsWith(player.getName().toLowerCase())){
					if (region.getId().substring(player.getName().length()).equalsIgnoreCase(Integer.toString(chunkX) + Integer.toString(chunkZ))) {
						// If the region name starts with the player's name and ends with our chunkX and chunkY then assume that it was generated by economicWorldGuard and belongs to the player.
						//Get current member list
						RegionManager regionMan = container.get(player.getWorld());
						DefaultDomain currentMembers = regionMan.getRegion(region.getId()).getMembers();
						
						//Add member
						currentMembers.addPlayer(Bukkit.getPlayer(args[0]).getName());
						regionMan.getRegion(region.getId()).setMembers(currentMembers);
						
						player.sendMessage("Sharing chunk with " + args[0] + ".");
						if (debug) {
							Bukkit.getLogger().info("Region " + region.getId() + " shared with " + Bukkit.getPlayer(args[0]).toString());
						}
						return true;
					}
				}
			}
			player.sendMessage("You don't own a chunk here!");
			if (debug) {
				Bukkit.getLogger().info("No region was shared by sharechunk command.");
			}
			return true;
		}
		return true;
	}
}
